# Generated by Django 5.1.3 on 2024-12-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_booking_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(default='5150D6136A', max_length=10, unique=True),
        ),
    ]
